[package]
name = "pose-filter"
version = "0.2.0"
edition = "2021"
authors = ["YdrMaster"]
readme = "README.md"

[dependencies]
chassis = { path = "../chassis" }
nalgebra = "*"
rand = "*"
lazy_static = "*"
